# ============================================================================
# GitHub Actions CI/CD Template — ML/MLOps Projects
# ============================================================================
# Este workflow incluye:
#   - Linting y formateo
#   - Tests con cobertura
#   - Security scanning
#   - Build de Docker
#   - Opcional: Deploy automático
# ============================================================================

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Permite ejecución manual

# Cancelar workflows previos en el mismo branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.0"

jobs:
  # ============================================================================
  # Job 1: Linting y Formateo
  # ============================================================================
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linters
        run: |
          pip install ruff mypy

      - name: Run Ruff (linting)
        run: |
          ruff check src/ tests/ --output-format=github

      - name: Run Ruff (formatting check)
        run: |
          ruff format --check src/ tests/

      - name: Run MyPy (type checking)
        run: |
          mypy src/ --ignore-missing-imports
        continue-on-error: true  # No bloquea el build por ahora

  # ============================================================================
  # Job 2: Tests con Cobertura
  # ============================================================================
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: lint
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests with coverage
        run: |
          pytest tests/ \
            --cov=src \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=80 \
            -v

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false

  # ============================================================================
  # Job 3: Security Scanning
  # ============================================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install safety
        run: pip install safety pip-audit

      - name: Check dependencies for vulnerabilities (safety)
        run: |
          pip install -e . --quiet
          safety check --full-report
        continue-on-error: true

      - name: Check dependencies for vulnerabilities (pip-audit)
        run: pip-audit
        continue-on-error: true

      - name: Run Gitleaks (secrets detection)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ============================================================================
  # Job 4: Build Docker Image
  # ============================================================================
  docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================================
  # Job 5: Deploy (opcional, descomenta si necesitas)
  # ============================================================================
  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: [test, docker]
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   environment: production
  #   
  #   steps:
  #     - name: Deploy notification
  #       run: echo "Deploying to production..."
  #     
  #     # Aquí irían los pasos de deploy específicos
  #     # - AWS ECS/Lambda
  #     # - Google Cloud Run
  #     # - Kubernetes
  #     # etc.

  # ============================================================================
  # Job 6: Notify (opcional)
  # ============================================================================
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    if: always()
    
    steps:
      - name: Check job statuses
        run: |
          if [ "${{ needs.test.result }}" == "failure" ]; then
            echo "Tests failed!"
            exit 1
          fi
          echo "All checks passed!"
