version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  # Python dependencies - BankChurn-Predictor
  - package-ecosystem: "pip"
    directory: "/BankChurn-Predictor"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "BankChurn-Predictor"
    open-pull-requests-limit: 5

  # Python dependencies - NLPInsight-Analyzer
  - package-ecosystem: "pip"
    directory: "/NLPInsight-Analyzer"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "NLPInsight"
    open-pull-requests-limit: 5

  # Docker
  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5
