"""FastAPI application for Chicago Taxi Demand Pipeline.

Serves pre-computed hourly demand predictions from the batch pipeline.
Unlike online inference services, this API queries aggregated predictions
generated by the PySpark ETL + Dask batch prediction pipeline.

Endpoints:
    GET  /health          — Health check
    GET  /metrics         — Prometheus metrics
    GET  /demand          — Query demand predictions by area/hour
    GET  /areas           — List available community areas
    GET  /pipeline/status — Last ETL pipeline run status
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

try:
    from common_utils import get_logger

    logger = get_logger("chicagotaxi-demand")
except ImportError:
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

try:
    from prometheus_client import CONTENT_TYPE_LATEST, Counter, Histogram, generate_latest

    PROMETHEUS_AVAILABLE = True
    REQUEST_COUNT = Counter(
        "chicagotaxi_requests_total",
        "Total requests",
        ["method", "endpoint", "status"],
    )
    REQUEST_LATENCY = Histogram(
        "chicagotaxi_request_latency_seconds",
        "Request latency",
        ["endpoint"],
    )
except ImportError:
    PROMETHEUS_AVAILABLE = False

BASE_DIR = Path(__file__).resolve().parent.parent

# Global state
predictions_df: Optional[pd.DataFrame] = None
etl_metadata: Dict[str, Any] = {}
prediction_summary: Dict[str, Any] = {}
start_time = time.time()


def load_predictions() -> bool:
    """Load pre-computed predictions from Parquet."""
    global predictions_df, etl_metadata, prediction_summary

    try:
        pred_dir = Path(
            os.environ.get(
                "PREDICTIONS_PATH",
                str(BASE_DIR / "data" / "processed" / "taxi_predictions"),
            )
        )

        if not pred_dir.exists():
            logger.warning("Predictions directory not found: %s", pred_dir)
            return False

        parquet_files = list(pred_dir.glob("*.parquet")) + list(pred_dir.glob("**/*.parquet"))
        if not parquet_files:
            logger.warning("No parquet files found in predictions directory: %s", pred_dir)
            return False

        predictions_df = pd.read_parquet(pred_dir)
        logger.info("Loaded %d prediction rows from %s", len(predictions_df), pred_dir)

        # Load ETL metadata
        meta_path = BASE_DIR / "data" / "processed" / "taxi_trips_parquet" / "etl_metadata.json"
        if meta_path.exists():
            with open(meta_path) as f:
                etl_metadata = json.load(f)

        # Load prediction summary
        summary_path = pred_dir / "prediction_summary.json"
        if summary_path.exists():
            with open(summary_path) as f:
                prediction_summary = json.load(f)

        return True
    except Exception as e:
        logger.error("Failed to load predictions: %s", e)
        return False


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage application lifecycle."""
    success = load_predictions()
    if not success:
        logger.warning("Started without predictions loaded.")
    yield


app = FastAPI(
    title="ChicagoTaxi Demand Pipeline API",
    description="Batch-computed taxi demand predictions for Chicago (6.3M trips, PySpark ETL)",
    version="1.0.0",
    root_path=os.getenv("API_ROOT_PATH", ""),
    lifespan=lifespan,
)

_cors_origins = os.getenv("CORS_ORIGINS", "http://localhost:3000").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in _cors_origins],
    allow_credentials=True,
    allow_methods=["GET"],
    allow_headers=["Content-Type"],
)


# --- Pydantic Models ---


class HealthResponse(BaseModel):
    status: str
    predictions_loaded: bool
    total_predictions: int
    uptime_seconds: float
    version: str


class DemandResponse(BaseModel):
    pickup_community_area: int
    hour: int
    day_of_week: int
    is_weekend: int
    predicted_demand: float
    demand_category: str
    avg_fare: float
    avg_distance_miles: float


class PipelineStatus(BaseModel):
    raw_rows: int = 0
    clean_rows: int = 0
    drop_rate_pct: float = 0.0
    hourly_demand_rows: int = 0
    processing_time_seconds: float = 0.0
    throughput_rows_per_sec: int = 0
    spark_version: str = ""
    partitioning: str = ""
    compression: str = ""


class AreaSummary(BaseModel):
    area_id: int
    avg_demand: float
    peak_hour: int
    total_records: int


# --- Endpoints ---


@app.get("/", response_model=Dict[str, str])
async def root():
    return {
        "message": "ChicagoTaxi Demand Pipeline API",
        "version": "1.0.0",
        "docs": "/docs",
        "health": "/health",
        "pipeline": "PySpark ETL + Dask Batch Prediction",
    }


@app.get("/health", response_model=HealthResponse)
async def health_check():
    total = len(predictions_df) if predictions_df is not None else 0
    return HealthResponse(
        status="healthy" if predictions_df is not None else "degraded",
        predictions_loaded=predictions_df is not None,
        total_predictions=total,
        uptime_seconds=time.time() - start_time,
        version="1.0.0",
    )


@app.get("/metrics")
async def metrics():
    """Prometheus-compatible metrics endpoint."""
    if PROMETHEUS_AVAILABLE:
        from starlette.responses import Response

        return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)
    return {"error": "prometheus_client not installed"}


@app.get("/demand", response_model=List[DemandResponse])
async def get_demand(
    area: Optional[int] = Query(None, description="Pickup community area ID (1-77)"),
    hour: Optional[int] = Query(None, ge=0, le=23, description="Hour of day"),
    day_of_week: Optional[int] = Query(None, ge=1, le=7, description="Day of week (1=Sun, 7=Sat)"),
    limit: int = Query(50, ge=1, le=1000, description="Max results"),
):
    """Query pre-computed demand predictions."""
    if predictions_df is None:
        raise HTTPException(status_code=503, detail="Predictions not loaded")

    start = time.time()
    df = predictions_df.copy()

    if area is not None:
        df = df[df["pickup_community_area"] == area]
    if hour is not None:
        df = df[df["hour"] == hour]
    if day_of_week is not None:
        df = df[df["day_of_week"] == day_of_week]

    df = df.sort_values("predicted_demand", ascending=False).head(limit)

    if PROMETHEUS_AVAILABLE:
        REQUEST_COUNT.labels(method="GET", endpoint="/demand", status="200").inc()
        REQUEST_LATENCY.labels(endpoint="/demand").observe(time.time() - start)

    results = []
    for _, row in df.iterrows():
        results.append(
            DemandResponse(
                pickup_community_area=int(row.get("pickup_community_area", 0)),
                hour=int(row.get("hour", 0)),
                day_of_week=int(row.get("day_of_week", 0)),
                is_weekend=int(row.get("is_weekend", 0)),
                predicted_demand=round(float(row.get("predicted_demand", 0)), 2),
                demand_category=str(row.get("demand_category", "unknown")),
                avg_fare=round(float(row.get("avg_fare", 0)), 2),
                avg_distance_miles=round(float(row.get("avg_distance_miles", 0)), 2),
            )
        )
    return results


@app.get("/areas", response_model=List[AreaSummary])
async def list_areas():
    """List community areas with demand summaries."""
    if predictions_df is None:
        raise HTTPException(status_code=503, detail="Predictions not loaded")

    grouped = (
        predictions_df.groupby("pickup_community_area")
        .agg(
            avg_demand=("predicted_demand", "mean"),
            peak_hour=(
                "predicted_demand",
                lambda x: predictions_df.loc[x.idxmax(), "hour"] if len(x) > 0 else 0,
            ),
            total_records=("predicted_demand", "count"),
        )
        .reset_index()
    )

    results = []
    for _, row in grouped.sort_values("avg_demand", ascending=False).iterrows():
        results.append(
            AreaSummary(
                area_id=int(row["pickup_community_area"]),
                avg_demand=round(float(row["avg_demand"]), 2),
                peak_hour=int(row["peak_hour"]),
                total_records=int(row["total_records"]),
            )
        )
    return results


@app.get("/pipeline/status", response_model=PipelineStatus)
async def pipeline_status():
    """Return last ETL pipeline run metadata."""
    if not etl_metadata:
        raise HTTPException(status_code=404, detail="No ETL metadata found")
    return PipelineStatus(**{k: v for k, v in etl_metadata.items() if k in PipelineStatus.model_fields})


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
