---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-workload
  namespace: ml-portfolio
  annotations:
    iam.gke.io/gcp-service-account: ml-portfolio-gke-workload@ml-portfolio-duque-om-202602.iam.gserviceaccount.com
